### ISSUE TITLE
ww not implemented yet

### ISSUE THREAD

**Issue by nattlip** [mruiter/com.gledopto#1]
ww not implemented yet rgb works, . via the hue bridge ww and rgb works but not at the same time

**Comment by motor4all** [comment]
+1! Will it work if you simply change the device ID to 544 (that is the ID in my case)

**Comment by motor4all** [comment]
> I have gledopto led dimmer WW. Device ID 256.
> It only works on and off.
> How do I change my ID? Through app Athom home in Windows. It will work dimmer ? Thanx
I think Marco has upload the new code to Athom. In his new code there is support for the WW dimmer. I use a clone of the code from Marco and added the WW dimmer with ID 256, but only with the on-off and dim function. As far as I can see has Marco combined it in one device for Homey, but than you will also get the ability to change color what of course will not work on the WW dimmer only.

**Comment by Agent848** [comment]
When will the update be? Still can not dim WW. Update app? Date?

**Comment by bvdbos** [comment]
Guess this one is fixed?

**Comment by Agent848** [comment]
Hello. Today I've updated Gledopto 1.1.1 beta. i unpair and pair my gledopto ww dimmer. Now turning on and dimming is working. Thank you. 
Now testing testing testing...

**Comment by Agent848** [comment]
Now dimming with xiaomi cube (rotating). Super.
