### ISSUE TITLE
Homey App page - models added

### ISSUE THREAD

**Issue by glennhmjoat** [mruiter/com.gledopto#14]
Thanks for your work so far, great to see someone is helping with these devices

I know its a tiny request , but can you please add the model numbers next to the pics of the supported controllers (like on the GL-007 bulb), since half of them look almost exactly the same.
hopefully this may help someone else not do what I did and buy an unsupported controller.

thanks heaps

![image](https://user-images.githubusercontent.com/45816076/52993191-3c115700-3478-11e9-9e67-f6065b3d019e.png)

**Comment by mruiter** [comment]
Structure changed in upcoming SDKv3 version
