### ISSUE TITLE
GLEDOPTO - GL-C-009 Dimmer led controller

### ISSUE THREAD

**Issue by glennhmjoat** [mruiter/com.gledopto#15]
would it be possible to please add support for this Dimmer / LED controller
GL-C-009
Dimmer - LED Controller

as a Basic Zigbee device it dims ok, but it does not turn on and off
if there is anything you need to help with this just ask, and i will try and help if i can
thanks

![gl-c-009 sett](https://user-images.githubusercontent.com/45816076/52993624-b1315c00-3479-11e9-893e-6440a376c4d1.jpg)

**Comment by jalbrink** [comment]
Same here. Can you please add it?

**Comment by Vasiliy-R** [comment]
Add this code to app.json
"drivers": [
        {
            "id": "led_dimmer",
            "name": {
                "en": "Gledopto Dimmer",
                "nl": "Gledopto Dimmer"
            },
            "mobile": {
                "components": [
                    {
                        "id": "icon",
                        "capabilities": [
                            "onoff"
                        ]
                    },
                    {
                        "id": "slider",
                        "capabilities": [
                            "dim"
                        ]
                    }
                ]
            },
            "class": "light",
            "capabilities": [
                "onoff",
                "dim"
            ],
            "capabilitiesOptions": {
                "onoff": {},
                "dim": {}
            },
            "images": {
                "large": "/drivers/gledopto_rgb/assets/images/large.jpg",
                "small": "/drivers/gledopto_rgb/assets/images/small.jpg"
            },
            "zigbee": {
                "manufacturerName": [
                    "GLEDOPTO"
                ],
                "productId": [
                    "GL-C-009"
                ],
                "deviceId": 256,
                "profileId": 49246,
                "learnmode": {
                    "instruction": {
                        "en": "1. Connect the LED product to the controller see section `wire connection`.\n 2. Start the device searching on the ZigBee Light Link Gateway, it could take some time.\nIf the Gateway does not find the device, plug power off/on or make a reset.\n3. The Gateway found your device and you can assign it to the different rooms/zones/groups.\n4. Now you can use the device.\n\nReset:\n1. Switch on your device.          2. Now switch off and on within 2 seconds.\n3. Repeat off/on four times.\n4. Reset is done when the device is switched on in the fifth time and the light stays on after blinking 4 times.",
                        "nl": "1. Connect the LED product to the controller see section `wire connection`.\n 2. Start the device searching on the ZigBee Light Link Gateway, it could take some time.\nIf the Gateway does not find the device, plug power off/on or make a reset.\n3. The Gateway found your device and you can assign it to the different rooms/zones/groups.\n4. Now you can use the device.\n\nReset:\n1. Switch on your device.          2. Now switch off and on within 2 seconds.\n3. Repeat off/on four times.\n4. Reset is done when the device is switched on in the fifth time and the light stays on after blinking 4 times."
                    }
                }
            },
            "settings": [
                {
                    "id": "transition_time",
                    "type": "number",
                    "label": {
                        "en": "Transition Time",
                        "nl": "Overgangstijd"
                    },
                    "hint": {
                        "en": "This setting determines the time in seconds it takes to dim from one level to another.",
                        "nl": "Deze instelling bepaalt de duur in seconden van het dimmen van een niveau naar een ander."
                    },
                    "value": 1,
                    "attr": {
                        "min": 0,
                        "max": 6553
                    }
                }
            ]
        }

**Comment by joostvkempen** [comment]
Can anyone confirm the code from @Vasiliy-R works? Is it tested? I want to order them, but only if I can use them with Homey....

**Comment by Vasiliy-R** [comment]
I have this dimer working with Homey for about a year

ср, 6 мая 2020 г. в 17:27, Joost van Kempen <notifications@github.com>:

**Comment by aageberg** [comment]
`Ages-iMac:com.gledopto-master aage$ homey app install
✓ Pre-processing app...
✓ Validating app...
✖ Homey App did not validate against level `debug`:
Filepath does not exist: drivers/led_dimmer
Not installing, please fix the validation issues first`

What have you done regarding to this @Vasiliy-R ? Did you create any folder/files for led_dimmer?

**Comment by joostvkempen** [comment]
I've added the code and all the files needed on my own github and created a pull request: https://github.com/mruiter/com.gledopto/pull/39

**Comment by mruiter** [comment]
Support is added in github and
