### ISSUE TITLE
Support for RGB Version

### ISSUE THREAD

**Issue by Asinke** [mruiter/com.gledopto#2]
Hi Marco,

Thanks for this nice app, I mistakenly ordered the RGB version. Can you please add support for that as well?

Device ID: 256
Profile ID: 49246

**Comment by gijsje** [comment]
I do have the same one and it is set as unknown zigbee controller.
Would it be possible to add this?

**Comment by Reemster** [comment]
The same problem here ;-) it will be nice if it can be added

**Comment by gijsje** [comment]
I use it now with the philips hue bridge works perfect that way

**Comment by Reemster** [comment]
I also use it now with the bridge. But the weird thing is.. i get 2 devices now. 1 for the colour and the another one for turn on/off the white leds on the ledstrip.

**Comment by flits** [comment]
Same here. Added as an "onbekend Zigbee" and only able to switch on/off.
![knipsel](https://user-images.githubusercontent.com/3659189/49393646-27071080-f732-11e8-8fca-88d42c887feb.JPG)

**Comment by laurenssss** [comment]
Following rgbw is also not supported, anyone can help?

![screenshot_20190105-155151_homey gen 2](https://user-images.githubusercontent.com/17315800/50725716-13204700-1102-11e9-9c4c-62cdd95c4609.jpg)

**Comment by flits** [comment]
Sorry cannot help.
I stopped trying and bought a Philips Hue Bridge.

**Comment by bvdbos** [comment]
Guess this one is fixed?

**Comment by laurenssss** [comment]
Is the one i mentioned added?

**Comment by bvdbos** [comment]
https://github.com/mruiter/com.gledopto/blob/c24127a8d0f36dcbdef8311edd2db052c0bb30a6/app.json#L100
So should work afaik...

**Comment by bvdbos** [comment]
https://github.com/mruiter/com.gledopto/blob/master/app.json#L100
so should work afaik...

**Comment by laurenssss** [comment]
OK I will give it a try this evening

**Comment by laurenssss** [comment]
Not fully working yet, it is a rgbw controller but gets added as a rgb cct controller 
I can control the color, but color in homey is not matching the actual strip color
Can not switch the device on or off, not responding to that

**Comment by mruiter** [comment]
SDKv3 reqrite for the new zigbee implementation is being made to solve this
