### ISSUE TITLE
Add support for GL-B-001Z & GL-B-007Z

### ISSUE THREAD

**Issue by quentinsch** [mruiter/com.gledopto#20]
Please add support for the RGB/CCT bulbs:

E27: GL-B-007Z
E14: GL-B-001Z

I think they are pretty much the same as the already supported devices.

**Comment by matrover** [comment]
+1 for the GL-B-001Z

**Comment by strejcd** [comment]
Hi, I would like to have GL-B-007Z too. Eager to donate if functioning.

Key | Value
-- | --
zb_profile_id | "49246"
zb_device_id | "528"
zb_ieee_addr | "0x00124b001ea81f7c"
zb_product_id | "GL-B-007Z"
zb_manufacturer_name | "GLEDOPTO"
energy_alwayson | false
energy_value_off | null
energy_value_on | null

**Comment by mruiter** [comment]
https://homey.app/nl-nl/app/com.gledopto/Gledopto-en-Tint-lampen-en-LED-Controllers-(ZigBee)/test/

**Comment by MevilVoronkevich** [comment]
GL-B-007Z no support
