### ISSUE TITLE
Gledopto GL-007-Z 

### ISSUE THREAD

**Issue by roywillemsgithub** [mruiter/com.gledopto#21]
Gledopto GL-007-Z not recognized by app.

**Comment by roywillemsgithub** [comment]
![5A596F5C-14D4-4E01-A442-A0FC4CF019F2](https://user-images.githubusercontent.com/48865643/54869925-a1ba7100-4d9f-11e9-9390-1c491d67e1b9.png)

**Comment by mruiter** [comment]
Is added in the SDKv3 rewrite
