### ISSUE TITLE
Not possible to pair ww-cw led controller

### ISSUE THREAD

**Issue by homeykev** [mruiter/com.gledopto#23]
In current released beta version it is not possible to pair with ww-cw led strip controller. I added the product-Id “GL-C-006” to code to get the app to pair. I can now control on/off and dim, but when changing the light temperature it doesn’t work and after that it is impossible to turn the lights off, dimming stays possible tough. Any ideas where I should take a look to fix this?

**Comment by Vasiliy-R** [comment]
I have exactly the same problem. Maybe someone found a solution?

**Comment by timpan8** [comment]
Same for me

**Comment by timpan8** [comment]
Okay I fixed it https://github.com/timpan8/com.gledopto

**Comment by mruiter** [comment]
Devices added inSDKv3 rewrite
