### ISSUE TITLE
Tint WW not possible to install

### ISSUE THREAD

**Issue by JustThe2ofUs** [mruiter/com.gledopto#24]
The pairing routine starts as usual but in the end the message appears saying „there’s no app been found for this device. It’s added as standard zigbee device“ ... which is a pity, as it’s not possible to use it properly according to its possibilities.

**Comment by mruiter** [comment]
Could you please supply me with the zigbee id's :
   "manufacturerName":
    "productId": 
    "deviceId": 
    "profileId": 

Then i can add it in the app
