### ISSUE TITLE
RGBW led controller GL-C-007

### ISSUE THREAD

**Issue by erwinklef** [mruiter/com.gledopto#28]

**Comment by erwinklef** [comment]
Is er ook een driver beschikbaar voor de RGBW led controller GL-C-007. Homel laad deze nu als een standaard Zigbee apparaat waarbij het apparaat alleen in en uitgeschakeld kan worden.

**Comment by ErikvanMaanen** [comment]
HI. Ik ben ook aan het wachten/hopen op de toevoeging van dit type.
Eventueel kan ik er eentje aanleveren als dat helpt.

**Comment by mruiter** [comment]
Is added in the latest v5 series firmware
