### ISSUE TITLE
Support for CCT version

### ISSUE THREAD

**Issue by coenboomkamp** [mruiter/com.gledopto#3]
Hi Marco,

Can you please add support for the Gledopto RGB-CCT version?

Device ID: 528
Profile ID: 49246

Would be great, thank you!

![schermafbeelding 2018-10-11 om 19 40 56](https://user-images.githubusercontent.com/34875500/46823398-60547d00-cd8e-11e8-8062-ef72419f7480.jpg)
![schermafbeelding 2018-10-11 om 19 41 16](https://user-images.githubusercontent.com/34875500/46823399-60547d00-cd8e-11e8-8e3a-35c460a57905.jpg)

**Comment by magtimmermans** [comment]
+1

**Comment by Rocodamelshe** [comment]
Looks to me the CCT version should work:

      "deviceId": [528 , 256],
      "profileId": 49246,

**Comment by magtimmermans** [comment]
Hi, Yes indeed. But it only ad a switch to put it on and off. You cannot change the color??

**Comment by motor4all** [comment]
After the device is added, is the icon a picture of a LedStrip? If not, it is not recognized by the Gledopto driver. It defaults than to a normal Zigbee device (with only on/off)

**Comment by magtimmermans** [comment]
No, it is not. Only on/off

**Comment by motor4all** [comment]
So it is not recognized. Are you sure the device ID is 528? Or better, can you check the device ID

**Comment by Rocodamelshe** [comment]
Must say mine is a tiny bit different:

![gledopto](https://user-images.githubusercontent.com/19249884/48673426-a648f180-eb41-11e8-888f-5885c4f355e3.jpg)

**Comment by Rocodamelshe** [comment]
Like the title of the app states:
Gledopto RGB Led Strip Controller (ZigBee)

**Comment by magtimmermans** [comment]
mmh, Would that be the problem? Your works oke? Can you send me the link where you bought it?

**Comment by igerka** [comment]
+1
I can only put it on and off =( 
several times did reset - did not help.

![2](https://user-images.githubusercontent.com/38116628/49143180-2837d800-f303-11e8-8036-cb7a74882394.JPG)
![1](https://user-images.githubusercontent.com/38116628/49143181-2837d800-f303-11e8-88dd-1ec9908c5ea8.jpg)

**Comment by magtimmermans** [comment]
I have received the one I ordered from the link above. Same issue. They have changed the housing. Thats why the case is different. I have 2 now both not working. 😊

**Comment by flits** [comment]
Same issue here.
Detected as a "onbekend ZigBee apparaat" and only able to switch on/off.

**Comment by Voxen1** [comment]
similar problem. It is found as an unknown device. DEVICE ED 528

**Comment by kotearaa** [comment]
Similar problem. It is found as an unknown device. DEVICE ID 528

**Comment by cab10** [comment]
Did a pull request. Added Product ID for GL-C007.
Sideloaded it and works for me.

But what is about the devices which show now manufacturer ID and product ID?

**Comment by magtimmermans** [comment]
Could you merge this into the master branch?

**Comment by igerka** [comment]
with the latest version only brightness adjustment! color does not change!

**Comment by Fred0022** [comment]
With me the same, only brightness is changed, no color adjustment. Is there still support here? :-(

Gledopto RGB-CCT DEVICE ID 528
