### ISSUE TITLE
GL-MC-001 TV led strip

### ISSUE THREAD

**Issue by strejcd** [mruiter/com.gledopto#31]
Hi, I would like to have GL-MC-001 implemented (TV led strip RGB-WW). Eager to donate too. Thanks

Key | Value
-- | --
zb_profile_id | "49246"
zb_device_id | "528"
zb_ieee_addr | "0x00124b001ee96d64"
zb_product_id | "GL-MC-001"
zb_manufacturer_name | "GLEDOPTO"
energy_value_off | null
energy_value_on | null

**Comment by mruiter** [comment]
I tried to add it into the sdkv3 rewrite. I dont have the devices so i have no idea if it works correct.

**Comment by tranceblast** [comment]
I have added this to homey:
![IMG_20201001_084120](https://user-images.githubusercontent.com/37779210/94777008-060db600-03c3-11eb-9e16-14f351f08aab.jpg)
And homey recognize it as this:
![IMG_20201001_084509](https://user-images.githubusercontent.com/37779210/94777080-23428480-03c3-11eb-8df4-2fb99b010088.jpg)
And it can't be controlled.

**Comment by mruiter** [comment]
Please send me the interview 

Verstuurd vanaf mijn iPhone

**Comment by tranceblast** [comment]
> Please send me the interview Verstuurd vanaf mijn iPhone
> […](#)
> Op 1 okt. 2020 om 08:51 heeft tranceblast ***@***.***> het volgende geschreven: ﻿ I have added this to homey: And homey recognize it as this: And it can't be controlled. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

I did 🙂

**Comment by mruiter** [comment]
New version is online 

Verstuurd vanaf mijn iPhone

**Comment by tranceblast** [comment]
I will try this in a minute. Will this also fix the problem with 008 2id?

**Comment by tranceblast** [comment]
It can now turn on/off and change color. 
Problem is that it's not possible to dim from 0% to for example 45% before it's been turned on.

When I try white this error is shown
![Screenshot_2020-10-01-15-54-20-011_app homey](https://user-images.githubusercontent.com/37779210/94820195-771f8e80-0400-11eb-927e-fd40ce03c292.jpg)

**Comment by mruiter** [comment]
did you do the re-pair ?

For now it seems to be a bit of a issue for the 2 id device to join. Since it doenst dow up as GL-C-0082ID model name but as 007 i will see if athom has some info on how to catch the device type on something else.

**Comment by tranceblast** [comment]
Yes I did a re-pair. Okey I will add the 2id to my hue bridge for now

**Comment by mruiter** [comment]
https://homey.app/nl-nl/app/com.gledopto/Gledopto-en-Tint-lampen-en-LED-Controllers-(ZigBee)/test/
