### ISSUE TITLE
Colour only on GL-C-008

### ISSUE THREAD

**Issue by yg-ht** [mruiter/com.gledopto#32]
Hey,
I recently installed a GL-C-008 but whilst it works on the most part, the warm white and cool white LEDs don't seem to work at all.  I don't think this is a physical fault with the device and I have read other areas of this repo that state there is a problem with white LEDs that require a re-write of the underlying ZigBee stack in Homey.  I was hoping you could expand on that a bit as I can't find any other reference to this and I can't see any obvious reasons why the white doesn't work.  What's more, I thought these devices were a clone of Philips Hue LightStrips and they work perfectly.
Thanks!

**Comment by strejcd** [comment]
Hi, many thanks for your effort. Seems zigbee rewrite sounding more and more in the Homey community. Lets hope Homey staff will improve that. Anyway I believe there must be a way now because Philips bulbs and strip work flawlessly for white temperature. Maybe Sebastian Johansson who wrote Philips Hue Zigbee App knows how to....  My solution for now is operating  lights in the original Philips Hue app not in Homey app. Cheers and apreciate your efforts.

**Comment by yg-ht** [comment]
Hey. I couldn't get the Phillips hue app to recognise my controllers and to be honest I started there before installing your app. Got any instructions on how to do that?

Interestingly though, I ordered a second 008 controller before your response came and a 007 turned up instead. This 007 doesn't work with either app.

Do you know what needed the rewrite in ZigBee core so I can check things?

I'm tempted to suggest the two apps merge. What do you think?

On February 21, 2020 9:50:29 PM GMT, strejcd <notifications@github.com> wrote:
>Hi, many thanks for your effort. Seems zigbee rewrite sounding more and
>more in the Homey community. Lets hope Homey staff will improve that.
>Anyway I believe there must be a way now because Philips bulbs and
>strip work flawlessly for white temperature. Maybe Sebastian Johansson
>who wrote Philips Hue Zigbee App knows how to....  My solution for now
>is operating  lights in the original Philips Hue app not in Homey app.
>Cheers and apreciate your efforts.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mruiter/com.gledopto/issues/32#issuecomment-589851942

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by glennhmjoat** [comment]
> Hi, many thanks for your effort. Seems zigbee rewrite sounding more and more in the Homey community. Lets hope Homey staff will improve that. Anyway I believe there must be a way now because Philips bulbs and strip work flawlessly for white temperature. Maybe Sebastian Johansson who wrote Philips Hue Zigbee App knows how to.... My solution for now is operating lights in the original Philips Hue app not in Homey app. Cheers and apreciate your efforts.

I think the philips controller connects via IP to homey like a bridge device, not zigbee, then it connects to its devices with its zigbee, which is why it works

**Comment by yg-ht** [comment]
Hey,

There are two different Hue apps - one that uses the bridge like you describe and another that is direct to the end device via ZigBee. It is definitely possible, just don't know how yet.

Thanks

On February 29, 2020 7:49:42 PM GMT, glennhmjoat <notifications@github.com> wrote:
>> Hi, many thanks for your effort. Seems zigbee rewrite sounding more
>and more in the Homey community. Lets hope Homey staff will improve
>that. Anyway I believe there must be a way now because Philips bulbs
>and strip work flawlessly for white temperature. Maybe Sebastian
>Johansson who wrote Philips Hue Zigbee App knows how to.... My solution
>for now is operating lights in the original Philips Hue app not in
>Homey app. Cheers and apreciate your efforts.
>
>I think the philips controller connects via IP to homey like a bridge
>device, not zigbee, then it connects to its devices with its zigbee,
>which is why it works
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mruiter/com.gledopto/issues/32#issuecomment-592987487

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mruiter** [comment]
Should be fixed in the upcoming sdkv3 rewrite
