### ISSUE TITLE
Homey v5

### ISSUE THREAD

**Issue by tranceblast** [mruiter/com.gledopto#40]
Hi, when will this app have support for Homey v5? And does the homey app have support for Rgb+cct-controller 2id and Rgb+cct-controller 1id?

**Comment by joostvkempen** [comment]
Please @mruiter could you give some reaction on the development of this app regarding Homey V5 (SDK3/Zigbee Rewrite) ? Maybe we can help? Or look for an alternative solution? Any reaction would be appreciated.

**Comment by tranceblast** [comment]
Is there any plans for rewrite the app for homey v5?

**Comment by mruiter** [comment]
There is a SDKv3 version in the making
