### ISSUE TITLE
Can you please add suport for GL-G-001Z

### ISSUE THREAD

**Issue by JohanAlvedal** [mruiter/com.gledopto#41]
Hello
recently bought a GL-G-001Z lamp to be able to have outdoors. so although the app did not support it, you can add that light and I would be very grateful.

//Johan Ä

**Comment by mruiter** [comment]
Could you please supply me with the zigbee id's :
   "manufacturerName":
    "productId": 
    "deviceId": 
    "profileId": 

Then i can add it in the app

**Comment by JohanAlvedal** [comment]
Hi data i as follows 
"manufacturerName”: GLEDOPTO
"productId”: GL-G-001Z
"deviceId”: 528
"profileId”: 49246

Regards Johan Ä

**Comment by mruiter** [comment]
Support has been added to the sdkv3 app available on GitHub for testing 

Verstuurd vanaf mijn iPhone

**Comment by mruiter** [comment]
https://homey.app/nl-nl/app/com.gledopto/Gledopto-en-Tint-lampen-en-LED-Controllers-(ZigBee)/test/
