### ISSUE TITLE
Could you add support for GL-C-007

### ISSUE THREAD

**Issue by FulcoNerra** [mruiter/com.gledopto#42]
The "apparaten" available in the Homey app don't work on this controller. I tried all versions on the Homey app as in the homey "verbind je apparaat" menu. 
![IMG_4DA09C62AD0C-1](https://user-images.githubusercontent.com/72230807/94896558-1474d400-048e-11eb-8e12-493d4d21639f.jpeg)

You said that there already is a working version available as a reply to my review in the homey.app website. I did download the gledopto controllers from that site onto my Homey. Only the GL-C-008 turns the lights red and gives an on-off functionality. the RGB CCT doesn't find the GL-C-007 ledstrip controller.
Can you help?

**Comment by mruiter** [comment]
are you on firmware v5 of homey and run the app from github . v2 version of the app.

there are also versions with 2id of the 007 and 008 . those dont work yet 

Verstuurd vanaf mijn iPad

**Comment by FulcoNerra** [comment]
Thanks Marco for the reply.
In het nederlands verder dan maar :)?
Mijn Homey is versie 4.2.0. (Early 2019).
Zou dat het probleem zijn?
Ik heb gledopto gu10 spots en die doen het prima (gl-s-003z).

Ik heb github bekeken, maar ik snap niet hoe je een app vanaf github moet runnen via de homey.
Kan je me dat uitleggen/ link sturen?
Ik hoop dat ik de ledstrip aan de gang krijg..
Groeten,
Sander

**Comment by FulcoNerra** [comment]
I managed the install of the gledopto development homey apps. :) I tried GL-C-008, GL-C-009, GL-G-001Z RGB and RGB+CCT.
But still no functionality of my GL-C-007 ledstrip controller via homey. Just red light and "simple zigbee device" on and off functionality.
I'm going to order a different controller with a separate remote. Homey isn't working, it's more limited than I thought.
Thanks for the development of those apps!
Best regards,
Sander

**Comment by FulcoNerra** [comment]
Good afternoon!
Thank you for updating the drivers. Unfortunately I get “er is een onbekende fout opgetreden: [incompatible_app_version]” in command prompt.
De Homey is helemaal up to date.
Hebben jullie een idee?
Groet,
Sander

**Comment by FulcoNerra** [comment]
Good afternoon!
Thank you for updating the drivers. Unfortunately I get “er is een onbekende fout opgetreden: [incompatible_app_version]” in command prompt.
De Homey is helemaal up to date.
Hebben jullie een idee?
Groet,
Sander

**Comment by mruiter** [comment]
Did you install the test version or the normal one in the AppStore
The new version will only work on the v5 and up firmware that’s currently in experimental channel 

Verstuurd vanaf mijn iPhone

**Comment by mruiter** [comment]
Oh and when installing from you need to update you node homey libs to support the new sdkv3

Verstuurd vanaf mijn iPhone

**Comment by FulcoNerra** [comment]
Dear Marco, I'm at best at "sophisticated user" level, but no developer.
I don't think it's a good idea for me to install the experimental firmware (v5).
What do tou think?

**Comment by josser84** [comment]
> Dear Marco, I'm at best at "sophisticated user" level, but no developer.
> I don't think it's a good idea for me to install the experimental firmware (v5).
> What do you think? Will v5 be finalized any time soon?
> Thanks for your patience.

Absolutely wait for now

**Comment by mruiter** [comment]
https://homey.app/nl-nl/app/com.gledopto/Gledopto-en-Tint-lampen-en-LED-Controllers-(ZigBee)/test/
