### ISSUE TITLE
Tint GU10 WW found as TINT WW Bulb

### ISSUE THREAD

**Issue by derJan2001** [mruiter/com.gledopto#43]
Diagnose: 63706a11-a416-4d8f-87b2-a29a214bb9ea

My Tint GU10 WW was found as TINT WW Bulb @2.0.2
and Homey gives me a colorchanger to choose.

The GU10 Bulb worked finde with 1.x  

Thx for your work.

**Comment by mruiter** [comment]
Give the new test version a try 

https://homey.app/nl-nl/app/com.gledopto/Gledopto-en-Tint-lampen-en-LED-Controllers-(ZigBee)/test/
