### ISSUE TITLE
Gledopto GL-C-007 does not respond

### ISSUE THREAD

**Issue by nulant** [mruiter/com.gledopto#44]
Installed Homey v5. Tried Gledopto app both usual App Store v2 and developers version.
The GL-C-007 does not respond to any command (timed out...), just hangs in the green startup light.
When installing as a simple Zigbee device it does respond to the on/off command, so the device seems to be able to work.
What might be the problem? Is it maybe a 2ID version? Do you already have a solution for this problem?
Thank you a lot, Thomas

**Comment by mruiter** [comment]
Please provide the zigbee interview 

Verstuurd vanaf mijn iPhone

**Comment by nulant** [comment]
"ids": {
    "modelId": "GL-C-007",
    "manufacturerName": "GLEDOPTO"
  },
  "endpoints": {
    "endpointDescriptors": [
      {
        "endpointId": 11,
        "applicationProfileId": 49246,
        "applicationDeviceId": 528,
        "applicationDeviceVersion": 0,
        "_reserved1": 2,
        "inputClusters": [
          0,
          3,
          4,
          5,
          6,
          8,
          768
        ],
        "outputClusters": []
      },
      {
        "endpointId": 13,
        "applicationProfileId": 49246,
        "applicationDeviceId": 528,
        "applicationDeviceVersion": 0,
        "_reserved1": 2,
        "inputClusters": [
          4096
        ],
        "outputClusters": [
          4096
        ]
      }
    ],
    "endpoints": {
      "11": {
        "clusters": {
          "basic": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "identify": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "groups": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "scenes": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "onOff": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "levelControl": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "colorControl": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          }
        },
        "bindings": {}
      },
      "13": {
        "clusters": {
          "touchlink": {
            "attributes": "TIMEOUT",
            "commandsGenerated": "TIMEOUT",
            "commandsReceived": "TIMEOUT"
          }
        },
        "bindings": {
          "touchlink": {
            "attributes": "TIMEOUT",
            "commandsGenerated": "TIMEOUT",
            "commandsReceived": "TIMEOUT"
          }
        }
      }
    }
  }

**Comment by nulant** [comment]
The package of the controller says that it is a 1ID... The device is recognized and added to Homey without any problems however does not respond to any command from then. Reset, adding again, nothing seems to work unfortunately.
Did you say something about updating the node in the homey or should an 'experimental' upgrade to firmware v5 be enough?
Thanks! Thomas

**Comment by nulant** [comment]
"ids": {
    "modelId": "GL-C-007",
    "manufacturerName": "GLEDOPTO"
  },
  "endpoints": {
    "endpointDescriptors": [
      {
        "endpointId": 11,
        "applicationProfileId": 49246,
        "applicationDeviceId": 528,
        "applicationDeviceVersion": 0,
        "_reserved1": 2,
        "inputClusters": [
          0,
          3,
          4,
          5,
          6,
          8,
          768
        ],
        "outputClusters": []
      },
      {
        "endpointId": 13,
        "applicationProfileId": 49246,
        "applicationDeviceId": 528,
        "applicationDeviceVersion": 0,
        "_reserved1": 2,
        "inputClusters": [
          4096
        ],
        "outputClusters": [
          4096
        ]
      }
    ],
    "endpoints": {
      "11": {
        "clusters": {
          "basic": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "identify": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "groups": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "scenes": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "onOff": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "TIMEOUT",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "levelControl": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "colorControl": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          }
        },
        "bindings": {}
      },
      "13": {
        "clusters": {
          "touchlink": {
            "attributes": "TIMEOUT",
            "commandsGenerated": "TIMEOUT",
            "commandsReceived": "TIMEOUT"
          }
        },
        "bindings": {
          "touchlink": {
            "attributes": "TIMEOUT",
            "commandsGenerated": "TIMEOUT",
            "commandsReceived": "TIMEOUT"
          }
        }
      }
    }
  }

**Comment by nulant** [comment]
Sorry closed by accident

**Comment by mruiter** [comment]
I uploaded a new test version with a endpoint correction in it.
Hope it now works . 

https://homey.app/nl-nl/app/com.gledopto/Gledopto-en-Tint-lampen-en-LED-Controllers-(ZigBee)/test/

**Comment by nulant** [comment]
Dear Marco,
Thank you very much for your very quick action to fix this problem. Unbelievably it now works great and I am excited!! 
Thanks, Thomas

**Comment by mruiter** [comment]
Thank you for responding back so fast 😉

Great it works now 👊

Verstuurd vanaf mijn iPhone
