### ISSUE TITLE
GL-C-008 error message [expected_new_range_start_number]

### ISSUE THREAD

**Issue by EmielCapelle** [mruiter/com.gledopto#45]
Hi Marco. I am on homey v5 rc.48, got the latest appversion (v2.0.3).
Managed to pair a GL-C-008 but get an error when I want to adjust whites like in the title/image. 
I thought the new sdkv3 included zigbee rewrite but I'm still running into issues. Am I doing something wrong or am I mistakingly thinking the cct should already work? 
Any thoughts?  ![image](https://user-images.githubusercontent.com/57303315/102689742-c2c42600-4200-11eb-99b6-a0cdd25f8053.png)

**Comment by nulant** [comment]
I got the same error now trying to activate the whites on my 007, that was previously working great after Marco fixed my reported issue.
Probably something to do with Homey RC update? Thomas

**Comment by nulant** [comment]
"ids": {
    "modelId": "GL-C-007",
    "manufacturerName": "GLEDOPTO"
  },
  "endpoints": {
    "endpointDescriptors": [
      {
        "endpointId": 11,
        "applicationProfileId": 49246,
        "applicationDeviceId": 528,
        "applicationDeviceVersion": 0,
        "_reserved1": 2,
        "inputClusters": [
          0,
          3,
          4,
          5,
          6,
          8,
          768
        ],
        "outputClusters": []
      },
      {
        "endpointId": 13,
        "applicationProfileId": 49246,
        "applicationDeviceId": 528,
        "applicationDeviceVersion": 0,
        "_reserved1": 2,
        "inputClusters": [
          4096
        ],
        "outputClusters": [
          4096
        ]
      }
    ],
    "endpoints": {
      "11": {
        "clusters": {
          "basic": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "identify": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "groups": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "scenes": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "onOff": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "levelControl": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "colorControl": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          }
        },
        "bindings": {}
      },
      "13": {
        "clusters": {
          "touchlink": {}
        },
        "bindings": {
          "touchlink": {}
        }
      }
    }
  }

**Comment by technik242** [comment]
Hello Marco,
the same problem with the GL-D-004z Dowlights.
+
all colors turn into blue and white when the intensity is reduced.
Greetings from Germany

**Comment by josser84** [comment]
@mruiter this might be due to missing attributes. See my code in https://github.com/mruiter/com.gledopto/issues/12#issuecomment-702739065

Let me know if I can help with anything. Gledopto makes nice affordable products, so good integration with Homey would be very nice. They also seem to be quite responsive on reddit in case some help is needed from them https://www.reddit.com/r/Gledopto/&ved=2ahUKEwiep6PS5ITuAhXD-6QKHckBAbgQFjAAegQIAhAD&usg=AOvVaw3UWGygzV0BjI3NaXpGNfjP

**Comment by josser84** [comment]
> Hello Marco,
> the same problem with the GL-D-004z Dowlights.
> +
> all colors turn into blue and white when the intensity is reduced.
> Greetings from Germany

Please create separate issues for different products

**Comment by josser84** [comment]
> Hi Marco. I am on homey v5 rc.48, got the latest appversion (v2.0.3).
> Managed to pair a GL-C-008 but get an error when I want to adjust whites like in the title/image.
> I thought the new sdkv3 included zigbee rewrite but I'm still running into issues. Am I doing something wrong or am I mistakingly thinking the cct should already work?
> Any thoughts? ![image](https://user-images.githubusercontent.com/57303315/102689742-c2c42600-4200-11eb-99b6-a0cdd25f8053.png)

Do you know if you are using the 1ID or 2ID?

**Comment by nulant** [comment]
I am on the 1ID version of the GL-C-007

**Comment by josser84** [comment]
> I am on the 1ID version of the GL-C-007
 
GL-C-007 =/= GL-C-008 for which this ticket is created. Please continue in the other already created ticket: https://github.com/mruiter/com.gledopto/issues/42

**Comment by josser84** [comment]
@EmielCapelle FYI, the GL-C-008 1ID seems to be working fine according to this comment: https://github.com/mruiter/com.gledopto/issues/12#issuecomment-730632626

**Comment by nulant** [comment]
> > I am on the 1ID version of the GL-C-007
> 
> GL-C-007 =/= GL-C-008 for which this ticket is created. Please continue in the other already created ticket: #42

I have the same error on my 007 and therefore I replied to this issue. A couple of weeks ago the 007 worked without any troubles...

**Comment by nulant** [comment]
Any news regarding this issue?

**Comment by EmielCapelle** [comment]
Sorry lost track of this issue due to a temp shift in automation focus 😬. I think I'm on the 2(ar8f) in my case. Can't find any other corresponding numbers but you can see for yourself. I'll add a picture.

**Comment by EmielCapelle** [comment]
> > Hi Marco. I am on homey v5 rc.48, got the latest appversion (v2.0.3).
> 
> > Managed to pair a GL-C-008 but get an error when I want to adjust whites like in the title/image.
> 
> > I thought the new sdkv3 included zigbee rewrite but I'm still running into issues. Am I doing something wrong or am I mistakingly thinking the cct should already work?
> 
> > Any thoughts? ![image](https://user-images.githubusercontent.com/57303315/102689742-c2c42600-4200-11eb-99b6-a0cdd25f8053.png)
> 
> 
> 
> Do you know if you are using the 1ID or 2ID?

I guess 2(ar8f). See my previous post.

**Comment by nulant** [comment]
1id vs 2id is indicated by a ‘check mark’ on the ‘short side’ of the controller package

**Comment by EmielCapelle** [comment]
> 1id vs 2id is indicated by a ‘check mark’ on the ‘short side’ of the controller package 

Can't find any checkmarks, stickers or indications apart from the printed stuff which is not refering to anything that comes close to 1 or 2id. Any tips? Can I find it in the device parameters for instance?

**Comment by nulant** [comment]
Marco, do you expert any improvements regarding this issue?

**Comment by josser84** [comment]
Some good news and some bad news.

- The bad news is that some attributes are just not set by the controller (colorTempPhysicalMinMireds and colorTempPhysicalMaxMireds; https://etc.athom.com/zigbee_cluster_specification.pdf page 5-4 for more info; this is the same issue as I mentioned earlier). 
-- There are 2 solutions for this:
---  We ask Athom to provide an easy way to set them manually
--- all clusters are added manually in the code to solve this
- The good news is that I recently ordered a new one (1ID) and that one works just fine with the existing code out of the box

I'm first going to try to contact Athom to see if they can help me. But looking at my previous encounter with them, I'm not very hopeful.

**Comment by josser84** [comment]
A surprising update. I found a workable solution, but there is a small drawback. The solution only works if the app is also restarted after adding the device. Although this is very minor and easy to overcome, it is not very user friendly. I'm going to see to create a PR with this solution and check if I can also fix the need to restart the app.

**Comment by josser84** [comment]
https://github.com/mruiter/com.gledopto/pull/55

**Comment by josser84** [comment]
@mruiter can you close this one please?

**Comment by nulant** [comment]
Dear Josser,
Thank you so much paying attention to this issue.
Could you also please update the GL-C-007 driver solving the same issue?
Looking forward to test the new version! Thomas

**Comment by josser84** [comment]
> Dear Josser,
> Thank you so much paying attention to this issue.
> Could you also please update the GL-C-007 driver solving the same issue?
> Looking forward to test the new version! Thomas

done with https://github.com/mruiter/com.gledopto/pull/57https://github.com/mruiter/com.gledopto/pull/57 
Keep in mind that I'm not able to test if this solution also works the 007. Please test thoroughly and report back
Don't forget to remove the device, add it again and restart the app!

**Comment by nulant** [comment]
Is it correct that your new code has not been incorporated yet?

**Comment by josser84** [comment]
> Is it correct that your new code has not been incorporated yet?

The PR is still open as you can see. You could use my branch to put the app on homey yourself if you would like to test it before it comes available in the official store (no idea when @mruiter will do that)

**Comment by mruiter** [comment]
Should be in test version

Verstuurd vanaf mijn iPhone

**Comment by nulant** [comment]
I downloaded @mruiter new/latest 'master' file (updated 4 hours ago) and uploaded with Terminal.
How is it possible to download your branch josser84 to test your modifications?
Thanks! Thomas

**Comment by josser84** [comment]
> Should be in test version Verstuurd vanaf mijn iPhone
> […](#)
> Op 16 mrt. 2021 om 21:00 heeft nulant ***@***.***> het volgende geschreven: ﻿ Is it correct that your new code has not been incorporated yet? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Marco, I assume @nulant was talking about the same fix for the GL-C-007. That PR (and another one) are still open: https://github.com/mruiter/com.gledopto/pulls

**Comment by josser84** [comment]
> I downloaded @mruiter new/latest 'master' file (updated 4 hours ago) and uploaded with Terminal.
> How is it possible to download your branch josser84 to test your modifications?
> Thanks! Thomas

You could clone [my forked code](https://github.com/josser84/com.gledopto/tree/master) and install it using the terminal. I just merged everything to the master.

**Comment by nulant** [comment]
@josser84 you fixed it!
After uploading the new code, removing the device, resetting and reinstalling the device, and finally restarting the app, my white colors light up again! Without restarting the app it did not work as you wrote. Thank you very much!

**Comment by mruiter** [comment]
Thx Josser !!! added in latest test version

**Comment by FVM00** [comment]
> A surprising update. I found a workable solution, but there is a small drawback. The solution only works if the app is also restarted after adding the device. Although this is very minor and easy to overcome, it is not very user friendly. I'm going to see to create a PR with this solution and check if I can also fix the need to restart the app.

This worked for me :-)
