### ISSUE TITLE
Add support for GL-B-008P

### ISSUE THREAD

**Issue by lhusoey** [mruiter/com.gledopto#47]
Hi 

Can you please add support for GL-B-008P "Dual White And Color" bulb?

ManufacturerID = GLEDOPTO
ProductID = GL-B-008P

I am running V5, so DeviceID and ProfileID is not displayed under advanced settings.

**Comment by lhusoey** [comment]
I made it work by modifying code. Making Pull request

**Comment by mruiter** [comment]
Thx looking forward to it 

Verstuurd vanaf mijn iPhone

**Comment by lhusoey** [comment]
Pull request made. First one so if I have done something wrong i am sorry :)
