### ISSUE TITLE
Tint rgb MLI, ZBT extendedcolor not working after last major update

### ISSUE THREAD

**Issue by nitrox50** [mruiter/com.gledopto#53]
Hi,
Tint rgb MLI, ZBT extendedcolor. They worked fine before upgrade. I can pair and upair them, they seem also to work as a zigbee relay but i can not turn them on or off, neither can i  change the color. The MLI white lights with dim function work well. Can i contribute anyhow to make them work again. Really tried everything but i looks programming. Already bruoght it to the Atom/Homey group with this answer  	
Boaz (Athom)
Feb 19, 2021, 12:28 GMT+1
Hi René,
Thank you for reporting this issue!
Unfortunately, this issue concerns an app that is not developed by us, but by a developer in our community.
You can contact the developer of this app via the Appstore. Please report this issue to this developer so he is aware of this issue.
https://github.com/mruiter/com.gledopto/issues
If you have any issues regarding the Homey software or mobile app, feel free to contact us again.
Best Regards,
Boaz
The Athom support team.
Stay posted on Facebook by liking our page: https://www.facebook.com/homey !

Cheers, Rene

**Comment by josser84** [comment]
@nitrox50 which upgrade do you mean?
what error are you getting?
can you do an interview and paste the result here?

**Comment by tom9865** [comment]
I guess these two issues are now being merged?

br,
Tom

**Comment by nitrox50** [comment]
I See two minor 5. updates for homey and a Tint upgrade. Gonna check then tomorrow. Today and tomorrow election days i have to work on voting location. I will let you know. Greetz, Rene

**Comment by josser84** [comment]
> I See two minor 5. updates for homey and a Tint upgrade. Gonna check then tomorrow. Today and tomorrow election days i have to work on voting location. I will let you know. Greetz, Rene

I also just did an update so the driver reflects the interview data

**Comment by mruiter** [comment]
https://homey.app/nl-nl/app/com.gledopto/Gledopto-en-Tint-lampen-en-LED-Controllers-(ZigBee)/test/

**Comment by nitrox50** [comment]
Nice. Everything works again. Thanx!
