### ISSUE TITLE
gl-g-001zs not supported

### ISSUE THREAD

**Issue by ellekebelleke** [mruiter/com.gledopto#59]
When installing GLEDOPTO garden spotlight gl g 001zs on Homey, it's installed as an unrecognized device, therefore hue is not working.
Would it be possible to add this to the list of supported devices?

**Comment by mruiter** [comment]
If you supply the interview of the device from the developers.athom.com page I can 

Verstuurd vanaf mijn iPhone

**Comment by ellekebelleke** [comment]
"ids": {
    "modelId": "GL-G-001ZS",
    "manufacturerName": "GLEDOPTO"
  },
  "endpoints": {
    "endpointDescriptors": [
      {
        "endpointId": 11,
        "applicationProfileId": 49246,
        "applicationDeviceId": 528,
        "applicationDeviceVersion": 0,
        "_reserved1": 2,
        "inputClusters": [
          0,
          3,
          4,
          5,
          6,
          8,
          768
        ],
        "outputClusters": []
      },
      {
        "endpointId": 13,
        "applicationProfileId": 49246,
        "applicationDeviceId": 528,
        "applicationDeviceVersion": 0,
        "_reserved1": 2,
        "inputClusters": [
          4096
        ],
        "outputClusters": [
          4096
        ]
      }
    ],
    "endpoints": {
      "11": {
        "clusters": {
          "basic": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "identify": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "groups": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "scenes": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "onOff": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "levelControl": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "colorControl": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          }
        },
        "bindings": {}
      },
      "13": {
        "clusters": {
          "touchlink": {}
        },
        "bindings": {
          "touchlink": {}
        }
      }
    }
  }

**Comment by ellekebelleke** [comment]
That would be great! Thanks.

**Comment by mruiter** [comment]
Please test the following


https://homey.app/nl-nl/app/com.gledopto/Gledopto-en-Tint-lampen-en-LED-Controllers-(ZigBee)/test/
