### ISSUE TITLE
gl-b-007z not supported 

### ISSUE THREAD

**Issue by MevilVoronkevich** [mruiter/com.gledopto#61]
Please add support gl-b-007z

**Comment by mruiter** [comment]
Please provide the interview data of the device from the zigbee 
developers page

MevilVoronkevich schreef op 2021-03-24 13:23:

**Comment by MevilVoronkevich** [comment]
> Please provide the interview data of the device from the zigbee developers page


  "ids": {
    "modelId": "GL-B-007Z",
    "manufacturerName": "GLEDOPTO"
  },
  "endpoints": {
    "endpointDescriptors": [
      {
        "endpointId": 11,
        "applicationProfileId": 49246,
        "applicationDeviceId": 528,
        "applicationDeviceVersion": 0,
        "_reserved1": 2,
        "inputClusters": [
          0,
          3,
          4,
          5,
          6,
          8,
          768
        ],
        "outputClusters": []
      },
      {
        "endpointId": 13,
        "applicationProfileId": 49246,
        "applicationDeviceId": 528,
        "applicationDeviceVersion": 0,
        "_reserved1": 2,
        "inputClusters": [
          4096
        ],
        "outputClusters": [
          4096
        ]
      }
    ],
    "endpoints": {
      "11": {
        "clusters": {
          "basic": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "identify": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "groups": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "scenes": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "onOff": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "levelControl": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "colorControl": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          }
        },
        "bindings": {}
      },
      "13": {
        "clusters": {
          "touchlink": {}
        },
        "bindings": {
          "touchlink": {}
        }
      }
    }
  }

**Comment by mruiter** [comment]
Please try 

https://homey.app/nl-nl/app/com.gledopto/Gledopto-en-Tint-lampen-en-LED-Controllers-(ZigBee)/test/

**Comment by MevilVoronkevich** [comment]
> Please try
> 
> https://homey.app/nl-nl/app/com.gledopto/Gledopto-en-Tint-lampen-en-LED-Controllers-(ZigBee)/test/

Thank.  light bulb added
