### ISSUE TITLE
Feature request : Animations

### ISSUE THREAD

**Issue by mrmannetje** [mruiter/com.gledopto#69]
Hi,

Thanks for your efforts on this app, absolutely love it and I've replaced nearly all my Fibaro RGBW for Gledopto. 
One thing I hope you might can add is the option to select animations as a that card. The Fibaro app does support that and in a few cases I really liked it. Attached you find a screenshot how it looks used in a flow via the Fibaro app.

I really hope it's an App feature and not a hardware feature but I don't know.
What I do know is that I'll sponsor you a crate of beer if your can fix it!

Thanks.

<img width="444" alt="Schermafbeelding 2021-05-17 om 21 12 35" src="https://user-images.githubusercontent.com/46524677/118543518-a3e8a200-b754-11eb-9a19-88def8dfadb2.png">

**Comment by mruiter** [comment]
Sorry , these animations are build into the hardware of fibaro.
Gledopto hasnt got this
