### ISSUE TITLE
Gledopto GU10

### ISSUE THREAD

**Issue by Pim65** [mruiter/com.gledopto#8]
Hi 
Is there a possibility that you could add the rgbww bulbs as well in Homey?
It works with this app, but only on 2 leds.
He doesn’t recognize it as a bulb ofcourse.
If needed i can send you one.

Thanks

Pim

**Comment by bvdbos** [comment]
Pim, could you give the following from your device - settings - advanced :
Manufacturer :
Product ID : 
DeviceId : 
ProfileId:

**Comment by Pim65** [comment]
Hi Bas,

See attached,
I saw you made some changes already, but still he sees it as a generic z wave unit (Unknown Zigbee device in Homey
Color changes etc works but only 2 of the leds are working. (I tried 4)

Thanks

Pim


________________________________
Van: Bas van den Bosch <notifications@github.com>
Verzonden: maandag 11 februari 2019 11:51
Aan: mruiter/com.gledopto
CC: Pim65; Author
Onderwerp: Re: [mruiter/com.gledopto] Gledopto GU10 (#8)


Pim, could you give the following from your device - settings - advanced :
Manufacturer :
Product ID :
DeviceId :
ProfileId:

**Comment by bvdbos** [comment]
Guess attachments and GH don't work together. Could you drag and drop it in Github?

**Comment by Pim65** [comment]
![img_20190212_064827](https://user-images.githubusercontent.com/40526333/52634499-a9951480-2ec7-11e9-8f51-53fe0f1c4c19.jpg)

![img_20190212_064844](https://user-images.githubusercontent.com/40526333/52634507-aef25f00-2ec7-11e9-8bca-42dc9456a568.jpg)
![screenshot_2019-02-12-06-50-44](https://user-images.githubusercontent.com/40526333/52634510-b0bc2280-2ec7-11e9-928e-1c16014f97b4.jpg)
![screenshot_2019-02-12-06-51-06](https://user-images.githubusercontent.com/40526333/52634513-b31e7c80-2ec7-11e9-8a83-04eeff0e387d.jpg)

**Comment by Pim65** [comment]
I hope this works

**Comment by bvdbos** [comment]
Thanks, will fix it tonight...

**Comment by Pim65** [comment]
Hi Bas,

It is also not possible to delete devices.
They will be deleted from homey, but the button is still active but not working..even not in parking mode and also not with resetting the complete zigbee network.

Verstuurd door Outlook<http://taps.io/outlookmobile> voor Android

________________________________

**Comment by Pim65** [comment]
Hi Bas,

Any update?

Thanks so far!

Pim

**Comment by bvdbos** [comment]
The fix is taken into the repository, guess Athom has to approve it for the appstore still. But if you want you can install it with the CLI.

**Comment by Pim65** [comment]
Thanks for the update.
I did wrote Athom support to fix the bug of deleting zigbee devices.
They are working on it.

Thanks!

**Comment by glennhmjoat** [comment]
re the removal of broken zigbee devices, ... this worked for me where i had shepherd device errors

- re add the device again
- you will get the duplicate device error,
- unplugged the device, and go through the remove device steps
- the device couldnt be found, but this time and you should get the “do you want to remove it anyway message”
- click "remove"
- go through the normal add device process 
- done

This worked a treat, my 5 broken zigbee devices now all work again
